/*
Initial version of sentinelx (Ksentinel)
Kernel Syscalls Integrity Monitor

Written by @MatheuZSecurity

Owner of Rootkit Researchers
Join us
https://discord.gg/66N5ZQppU7
*/

#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/kprobes.h>
#include <linux/workqueue.h>
#include <linux/slab.h>
#include <linux/version.h>
#include <linux/mutex.h>
#include <linux/list.h>
#include <linux/uaccess.h>
#include <linux/kallsyms.h>
#include <linux/kobject.h>
#include <linux/proc_fs.h>
#include <linux/string.h>
#include <linux/netfilter.h>
#include <linux/user_namespace.h>
#include <linux/sched.h>
#include <linux/sched/signal.h>  /* for_each_process_thread */

#ifdef CONFIG_X86_64
#include <asm/msr.h>
#include <asm/special_insns.h>
#include <asm/processor-flags.h>
#endif
#include <linux/set_memory.h>

/*
 * sentinelx_key.h is auto-generated by the Makefile before compilation.
 * It defines:  #define UNLOCK_KEY "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
 * The key never appears in module parameters, modinfo, or sysfs.
 */

#include "sentinelx_key.h"

MODULE_LICENSE("GPL");
MODULE_AUTHOR("MatheuZSecurity");
MODULE_DESCRIPTION("sentinelx: kernel integrity monitor");
MODULE_VERSION("1.0");

static unsigned int period_ms = 2000;
module_param(period_ms, uint, 0644);
MODULE_PARM_DESC(period_ms, "Check interval in milliseconds");

static char *sym_prefixes = "sys_,__x64_sys_,do_sys_,ksys_";
module_param(sym_prefixes, charp, 0444);
MODULE_PARM_DESC(sym_prefixes, "Comma-separated symbol prefixes to watch");

static char *extra_syms = "";
module_param(extra_syms, charp, 0444);
MODULE_PARM_DESC(extra_syms, "Comma-separated extra symbol names to watch");

static bool anti_unload = true;
module_param(anti_unload, bool, 0444);
MODULE_PARM_DESC(anti_unload, "Prevent rmmod (default: true)");

#define PROLOGUE_BYTES     16
#define MAX_WATCH_SYMS     1024
#define NR_SYSCALLS_WATCH  512
#define KSG_PROC_NAME      ".ksctl"

#define ENDBR64_B0   0xF3
#define ENDBR64_B1   0x0F
#define ENDBR64_B2   0x1E
#define ENDBR64_B3   0xFA
#define ENDBR64_LEN  4

#define OPCODE_JMP_REL32   0xE9
#define OPCODE_CALL_REL32  0xE8
#define OPCODE_JMP_IND_HI  0xFF
#define OPCODE_JMP_IND_LO  0x25

static const char * const sensitive_syms[] = {
	"filldir",
	"filldir64",
	"compat_filldir",
	"__vfs_getattr",
	"do_getdents64",
	"vfs_getdents",
	"tcp4_seq_show",
	"tcp6_seq_show",
	"udp4_seq_show",
	"udp6_seq_show",
	"raw_seq_show",
	"packet_seq_show",
	"proc_pid_readdir",
	"proc_readdir",
	"vfs_read",
	"vfs_write",
	"vfs_open",
	"vfs_unlink",
	"vfs_rename",
	"do_filp_open",
	"do_sys_openat2",
	"commit_creds",
	"prepare_kernel_cred",
	"security_bprm_check",
	"security_file_open",
	"security_inode_permission",
	"cap_capable",
	"load_module",
	"free_module",
	"__x64_sys_delete_module",
	"audit_log_start",
	"audit_log_end",
	"__audit_syscall_entry",
	"__audit_syscall_exit",
	"nf_hook_slow",
	"nf_register_net_hook",
	"nf_unregister_net_hook",
	"register_kprobe",
	"unregister_kprobe",
	"register_ftrace_function",
	"ftrace_set_filter",
	"do_execveat_common",
	"bprm_execve",
	"copy_process",
	"wake_up_new_task",
	"do_exit",
	"do_syscall_64",
	"do_int80_syscall_32",
	"do_mmap",
	"vm_mmap_pgoff",
	NULL
};

typedef unsigned long (*kallsyms_lookup_name_t)(const char *name);

#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 0)
typedef int (*kallsyms_on_each_symbol_t)(
	int (*fn)(void *, const char *, unsigned long), void *data);
#else
typedef int (*kallsyms_on_each_symbol_t)(
	int (*fn)(void *, const char *, struct module *, unsigned long),
	void *data);
#endif

static kallsyms_lookup_name_t    ksg_lookup_name;
static kallsyms_on_each_symbol_t ksg_on_each_symbol;
static struct mutex              *ksg_module_mutex;

static notrace int __init resolve_unexported_syms(void)
{
	struct kprobe kp = { .symbol_name = "kallsyms_lookup_name" };
	int ret;

	ret = register_kprobe(&kp);
	if (ret < 0) {
		pr_err("sentinelx: kprobe(kallsyms_lookup_name) failed: %d\n", ret);
		return ret;
	}
	ksg_lookup_name = (kallsyms_lookup_name_t)kp.addr;
	unregister_kprobe(&kp);

	if (!ksg_lookup_name) {
		pr_err("sentinelx: failed to resolve kallsyms_lookup_name\n");
		return -ENOENT;
	}

	ksg_on_each_symbol = (kallsyms_on_each_symbol_t)
		ksg_lookup_name("kallsyms_on_each_symbol");
	if (!ksg_on_each_symbol) {
		pr_err("sentinelx: failed to resolve kallsyms_on_each_symbol\n");
		return -ENOENT;
	}

	ksg_module_mutex = (struct mutex *)ksg_lookup_name("module_mutex");
	if (!ksg_module_mutex) {
		pr_err("sentinelx: failed to resolve module_mutex\n");
		return -ENOENT;
	}

	return 0;
}

static u64 notrace fnv1a64(const void *data, size_t len)
{
	const u8 *p = data;
	u64 h = 14695981039346656037ULL;
	size_t i;

	for (i = 0; i < len; i++) {
		h ^= (u64)p[i];
		h *= 1099511628211ULL;
	}
	return h;
}

static bool notrace buf_starts_with_endbr64(const u8 *buf)
{
	return (buf[0] == ENDBR64_B0 && buf[1] == ENDBR64_B1 &&
		buf[2] == ENDBR64_B2 && buf[3] == ENDBR64_B3);
}

static bool notrace prologue_looks_hooked(const u8 *buf)
{
	int off = buf_starts_with_endbr64(buf) ? ENDBR64_LEN : 0;
	const u8 *p = buf + off;

	if (off + 2 > PROLOGUE_BYTES)
		return false;
	if (p[0] == OPCODE_JMP_REL32)
		return true;
	if (p[0] == OPCODE_CALL_REL32)
		return true;
	if (p[0] == OPCODE_JMP_IND_HI && p[1] == OPCODE_JMP_IND_LO)
		return true;
	return false;
}

struct sym_entry {
	char          name[KSYM_NAME_LEN];
	unsigned long addr;
	u64           hash;
	u8            prologue[PROLOGUE_BYTES];
	bool          valid;
	bool          alerted;
};

static struct sym_entry *watchlist;
static int               watchlist_count;
static DEFINE_MUTEX(watchlist_mutex);

static bool notrace watchlist_add(const char *name, unsigned long addr)
{
	struct sym_entry *e;
	u8 buf[PROLOGUE_BYTES];
	int i;

	if (!addr || watchlist_count >= MAX_WATCH_SYMS)
		return false;

	for (i = 0; i < watchlist_count; i++) {
		if (watchlist[i].addr == addr)
			return false;
	}

	if (copy_from_kernel_nofault(buf, (const void *)addr, PROLOGUE_BYTES) != 0)
		return false;

	e = &watchlist[watchlist_count];
	strscpy(e->name, name, sizeof(e->name));
	e->addr  = addr;
	memcpy(e->prologue, buf, PROLOGUE_BYTES);
	e->hash  = fnv1a64(buf, PROLOGUE_BYTES);
	e->valid = true;
	e->alerted = false;
	watchlist_count++;
	return true;
}

struct iter_ctx {
	char *prefixes[32];
	int   n_prefixes;
};

static bool notrace matches_prefix(const char *name, const struct iter_ctx *ctx)
{
	int i;

	for (i = 0; i < ctx->n_prefixes; i++) {
		if (strncmp(name, ctx->prefixes[i], strlen(ctx->prefixes[i])) == 0)
			return true;
	}
	return false;
}

static int notrace sym_iter_cb_impl(void *data, const char *name, unsigned long addr)
{
	if (watchlist_count >= MAX_WATCH_SYMS)
		return 1;
	if (matches_prefix(name, data))
		watchlist_add(name, addr);
	return 0;
}

#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 0)
static int notrace sym_iter_cb(void *data, const char *name, unsigned long addr)
{
	return sym_iter_cb_impl(data, name, addr);
}
#else
static int notrace sym_iter_cb(void *data, const char *name,
		       struct module *mod __maybe_unused, unsigned long addr)
{
	return sym_iter_cb_impl(data, name, addr);
}
#endif

static void notrace parse_prefixes(struct iter_ctx *ctx, const char *param,
			   char *buf, size_t bufsz)
{
	char *tok, *pos;

	strscpy(buf, param, bufsz);
	pos = buf;
	ctx->n_prefixes = 0;
	while ((tok = strsep(&pos, ",")) != NULL &&
	       ctx->n_prefixes < (int)ARRAY_SIZE(ctx->prefixes)) {
		if (*tok)
			ctx->prefixes[ctx->n_prefixes++] = tok;
	}
}

/*
 * Symbols that sentinelx instruments with its own kprobes.
 *
 * These must NEVER enter the prologue watchlist. The kprobe subsystem
 * legitimately modifies their prologues (int3 on registration, then a
 * JMP after the asynchronous optimizer fires ~1s later). Hashing them
 * produces false [CHANGE — HOOK PATTERN] alerts on every load.
 *
 * These symbols are already monitored synchronously by their dedicated
 * kprobe handlers which fire on every call. Prologue hashing adds zero
 * detection value and only produces noise.
 *
 * MAINTENANCE: keep in sync with kprobes_init() below.
 */
static const char * const sentinelx_kprobed_syms[] = {
	"do_init_module",
	"wake_up_new_task",
	"do_exit",
	"prepare_kernel_cred",
	"commit_creds",
	"nf_register_net_hook",
	"register_ftrace_function",
	NULL,
};

static bool notrace is_self_kprobed(const char *name)
{
	const char * const *s;

	for (s = sentinelx_kprobed_syms; *s; s++)
		if (strcmp(name, *s) == 0)
			return true;
	return false;
}

/* Static buffers to keep build_watchlist() stack frame under 1024 bytes */
static char bw_prefix_buf[256];
static char bw_extra_buf[512];

static notrace int __init build_watchlist(void)
{
	struct iter_ctx ctx = {};
	char *prefix_buf = bw_prefix_buf;
	char *extra_buf  = bw_extra_buf;
	const char * const *p;
	int added_sensitive = 0, added_prefix, added_extra = 0;

	watchlist = kcalloc(MAX_WATCH_SYMS, sizeof(*watchlist), GFP_KERNEL);
	if (!watchlist)
		return -ENOMEM;

	for (p = sensitive_syms; *p; p++) {
		unsigned long addr;

		/*
		 * Skip symbols sentinelx kprobes directly — their prologues
		 * are intentionally modified by the kprobe subsystem and are
		 * already monitored synchronously. See sentinelx_kprobed_syms[].
		 */
		if (is_self_kprobed(*p))
			continue;

		addr = ksg_lookup_name(*p);
		if (addr && watchlist_add(*p, addr))
			added_sensitive++;
	}
	pr_info("sentinelx: %d sensitive symbols resolved\n", added_sensitive);

	parse_prefixes(&ctx, sym_prefixes, prefix_buf, 256);
	if (ctx.n_prefixes > 0) {
		int before = watchlist_count;

		ksg_on_each_symbol(sym_iter_cb, &ctx);
		added_prefix = watchlist_count - before;
		pr_info("sentinelx: %d prefix-matched symbols added\n", added_prefix);
	}

	if (extra_syms && *extra_syms) {
		char *tok, *pos;

		strscpy(extra_buf, extra_syms, 512);
		pos = extra_buf;
		while ((tok = strsep(&pos, ",")) != NULL) {
			unsigned long addr;

			if (!*tok)
				continue;
			addr = ksg_lookup_name(tok);
			if (!addr) {
				pr_warn("sentinelx: extra sym '%s' not found\n", tok);
				continue;
			}
			if (watchlist_add(tok, addr))
				added_extra++;
		}
		if (added_extra)
			pr_info("sentinelx: %d extra symbols added\n", added_extra);
	}

	pr_info("sentinelx: total watchlist = %d symbols\n", watchlist_count);
	return 0;
}

static void **sys_call_table_ptr;
static unsigned long sct_baseline[NR_SYSCALLS_WATCH];
static bool          sct_alerted[NR_SYSCALLS_WATCH];
static int sct_count;

static notrace void __init sct_build_baseline(void)
{
	int i;
	unsigned long entry;

	sys_call_table_ptr = (void **)ksg_lookup_name("sys_call_table");
	if (!sys_call_table_ptr) {
		pr_warn("sentinelx: sys_call_table not found, skipping SCT checks\n");
		return;
	}

	for (i = 0; i < NR_SYSCALLS_WATCH; i++) {
		if (copy_from_kernel_nofault(&entry, &sys_call_table_ptr[i],
					     sizeof(entry)) != 0)
			break;
		sct_baseline[i] = entry;
		sct_count++;
	}
	pr_info("sentinelx: sys_call_table @ %pK — %d entries baselined\n",
		sys_call_table_ptr, sct_count);
}

static void notrace sct_check(void)
{
	int i;
	unsigned long now;

	if (!sys_call_table_ptr || !sct_count)
		return;

	for (i = 0; i < sct_count; i++) {
		if (copy_from_kernel_nofault(&now, &sys_call_table_ptr[i],
					     sizeof(now)) != 0)
			continue;
		if (now != sct_baseline[i]) {
			if (!sct_alerted[i]) {
				char sym[KSYM_SYMBOL_LEN] = {};

				sprint_symbol(sym, now);
				pr_err("sentinelx: [SCT HOOK] syscall[%3d] expected=%pK got=%pK (%s)\n",
				       i, (void *)sct_baseline[i], (void *)now, sym);
				sct_alerted[i] = true;
			}
		} else {
			if (sct_alerted[i]) {
				pr_info("sentinelx: [SCT RESTORED] syscall[%3d] returned to baseline\n",
					i);
				sct_alerted[i] = false;
			}
		}
	}
}

#ifdef CONFIG_X86_64
#define MSR_LSTAR_ADDR 0xC0000082UL
static unsigned long lstar_baseline;
static unsigned long cr0_baseline;
static bool cr0_alerted;
static bool lstar_alerted;

static notrace void __init lstar_snapshot(void)
{
	rdmsrl(MSR_LSTAR_ADDR, lstar_baseline);
	pr_info("sentinelx: LSTAR baseline = %pK\n", (void *)lstar_baseline);
}

struct lstar_check_data {
	bool changed;
	unsigned long bad_val;
	int bad_cpu;
};

static void lstar_check_one_cpu(void *arg)
{
	struct lstar_check_data *d = arg;
	unsigned long now;

	rdmsrl(MSR_LSTAR_ADDR, now);
	if (now != lstar_baseline) {
		d->changed = true;
		d->bad_val = now;
		d->bad_cpu = smp_processor_id();
	}
}

static void notrace lstar_check(void)
{
	struct lstar_check_data d = {};

	/* MSR_LSTAR is per-CPU — check every CPU like cr0_check does */
	on_each_cpu(lstar_check_one_cpu, &d, 1);

	if (d.changed) {
		if (!lstar_alerted) {
			char sym[KSYM_SYMBOL_LEN] = {};

			sprint_symbol(sym, d.bad_val);
			pr_err("sentinelx: [LSTAR TAMPERED] CPU%d baseline=%pK now=%pK (%s)\n",
			       d.bad_cpu, (void *)lstar_baseline, (void *)d.bad_val, sym);
			lstar_alerted = true;
		}
	} else {
		if (lstar_alerted) {
			pr_info("sentinelx: [LSTAR RESTORED] baseline=%pK\n",
				(void *)lstar_baseline);
			lstar_alerted = false;
		}
	}
}

static notrace void __init cr0_snapshot(void)
{
	cr0_baseline = read_cr0();
	pr_info("sentinelx: CR0 baseline = 0x%lx (WP=%s)\n",
		cr0_baseline,
		(cr0_baseline & X86_CR0_WP) ? "enabled" : "disabled");
}

/* cr0_check runs on every CPU via on_each_cpu */
struct cr0_check_data {
	bool wp_disabled;
	bool changed;
	unsigned long bad_val;
	int bad_cpu;
};

static void cr0_check_one_cpu(void *arg)
{
	struct cr0_check_data *d = arg;
	unsigned long now = read_cr0();

	if (!(now & X86_CR0_WP)) {
		d->wp_disabled = true;
		d->bad_val     = now;
		d->bad_cpu     = smp_processor_id();
	}
	if (now != cr0_baseline) {
		d->changed = true;
		d->bad_val = now;
		d->bad_cpu = smp_processor_id();
	}
}

static void notrace cr0_check(void)
{
	struct cr0_check_data d = {};

	/* Check CR0 on every CPU — it is a per-CPU register */
	on_each_cpu(cr0_check_one_cpu, &d, 1);

	if (d.wp_disabled) {
		/*
		 * FIX: Removed the old  if (!cr0_alerted)  suppression guard.
		 *
		 * Root cause of run 3+ misses:
		 *   - Run 2: rootkit disables WP on CPU A, cr0_alerted = true
		 *   - Run 2 rmmod: rootkit restores WP on CPU B (process migrated)
		 *   - CPU A still has WP=0 — CR0_RESTORED never fires
		 *   - cr0_alerted stays true forever
		 *   - Run 3: WP disabled again, but if (!cr0_alerted) skips the
		 *     alert → MISSED
		 *
		 * Fix: fire [CR0 ALERT] on every tick while ANY cpu has WP=0.
		 * The eval's dmesg_since(pre_ts) catches the first occurrence
		 * after insmod regardless of how many times it fires.
		 * cr0_alerted is still set so CR0_RESTORED fires correctly
		 * once all CPUs restore WP (guaranteed by on_each_cpu in rootkit).
		 */
		pr_err("sentinelx: [CR0 ALERT] Write protection disabled "
		       "on CPU%d! val=0x%lx — possible rootkit.\n",
		       d.bad_cpu, d.bad_val);
		cr0_alerted = true;
	} else {
		if (cr0_alerted) {
			pr_info("sentinelx: [CR0 RESTORED] WP re-enabled on all CPUs\n");
			cr0_alerted = false;
		}
	}

	if (d.changed && d.wp_disabled == false)
		pr_warn("sentinelx: [CR0 CHANGED] baseline=0x%lx now=0x%lx on CPU%d\n",
			cr0_baseline, d.bad_val, d.bad_cpu);
}
#else
static inline void notrace lstar_snapshot(void) {}
static inline void notrace lstar_check(void)    {}
static inline void notrace cr0_snapshot(void)   {}
static inline void notrace cr0_check(void)      {}
#endif

/* ------------------------------------------------------------------ */
/*  Hidden Module Detection — Production Grade                        */
/* ------------------------------------------------------------------ */
#define MAX_MODULES_WATCH  256

struct mod_entry {
	char   name[MODULE_NAME_LEN];
	bool   alerted;
};

static struct mod_entry  mod_table[MAX_MODULES_WATCH];
static int               mod_table_count;

static bool notrace mod_tracked(const char *name)
{
	int i;
	for (i = 0; i < mod_table_count; i++)
		if (strncmp(mod_table[i].name, name, MODULE_NAME_LEN) == 0)
			return true;
	return false;
}

static notrace void __init modlist_snapshot(void)
{
	struct module *mod;

	mod_table_count = 0;

	list_for_each_entry(mod, &THIS_MODULE->list, list) {
		if (mod_table_count >= MAX_MODULES_WATCH)
			break;
		strscpy(mod_table[mod_table_count].name,
			mod->name, MODULE_NAME_LEN);
		mod_table[mod_table_count].alerted = false;
		mod_table_count++;
	}

	pr_info("sentinelx: module baseline = %d modules recorded\n",
		mod_table_count);
}

static bool notrace module_in_list(const char *name)
{
	struct module *mod;
	list_for_each_entry(mod, &THIS_MODULE->list, list)
		if (strncmp(mod->name, name, MODULE_NAME_LEN) == 0)
			return true;
	return false;
}

static void notrace modlist_check(void)
{
	struct module *mod;
	int i;

	if (!mutex_trylock(ksg_module_mutex))
		return;

	/* Layer 1A: Track any new modules that appeared */
	list_for_each_entry(mod, &THIS_MODULE->list, list) {
		if (strncmp(mod->name, THIS_MODULE->name,
			    MODULE_NAME_LEN) == 0)
			continue;
		if (!mod_tracked(mod->name) &&
		    mod_table_count < MAX_MODULES_WATCH) {
			strscpy(mod_table[mod_table_count].name,
				mod->name, MODULE_NAME_LEN);
			mod_table[mod_table_count].alerted = false;
			mod_table_count++;
		}
	}

	/* Layer 1B: Check if any tracked module vanished */
	for (i = 0; i < mod_table_count; i++) {
		struct mod_entry *e = &mod_table[i];

		if (strncmp(e->name, THIS_MODULE->name,
			    MODULE_NAME_LEN) == 0)
			continue;

		if (!module_in_list(e->name)) {
			if (!e->alerted) {
				pr_err("sentinelx: [MODULE HIDDEN] '%s' "
				       "vanished from module list — "
				       "rootkit using list_del()\n",
				       e->name);
				e->alerted = true;
			}
		} else {
			if (e->alerted) {
				pr_info("sentinelx: [MODULE RESTORED] "
					"'%s' back in module list\n",
					e->name);
				e->alerted = false;
			}
		}
	}

	mutex_unlock(ksg_module_mutex);
}

struct module_sect_attr {
	struct bin_attribute battr;
	unsigned long address;
};

struct module_sect_attrs {
	struct attribute_group grp;
	unsigned int nsections;
	struct module_sect_attr attrs[];
};

struct restore_info {
	struct kobject *parent;
	struct module_sect_attrs *attrs;
	const char *name;
};

static struct list_head      *saved_prev_module;
static struct restore_info   ksg_restore_info;
static struct proc_dir_entry *ksctl_proc;

static ssize_t notrace show_refcnt(const struct module_attribute *mattr,
			   struct module_kobject *mk, char *buffer)
{
	return sprintf(buffer, "%i\n", module_refcount(mk->mod));
}

static struct module_attribute modinfo_refcnt =
	__ATTR(refcnt, 0444, show_refcnt, NULL);

static struct module_attribute *modinfo_attrs[] = {
	&modinfo_refcnt,
	NULL,
};

static void notrace module_remove_modinfo_attrs(struct module *mod)
{
	struct module_attribute *attr;

	attr = &mod->modinfo_attrs[0];
	if (attr && attr->attr.name) {
		sysfs_remove_file(&mod->mkobj.kobj, &attr->attr);
		if (attr->free)
			attr->free(mod);
	}
	kfree(mod->modinfo_attrs);
}

static int notrace module_add_modinfo_attrs(struct module *mod)
{
	struct module_attribute *attr;
	struct module_attribute *temp_attr;
	int error = 0;

	mod->modinfo_attrs = kzalloc(
		(sizeof(struct module_attribute) * (ARRAY_SIZE(modinfo_attrs) + 1)),
		GFP_KERNEL);
	if (!mod->modinfo_attrs)
		return -ENOMEM;

	temp_attr = mod->modinfo_attrs;
	attr = modinfo_attrs[0];
	if (!attr->test || attr->test(mod)) {
		memcpy(temp_attr, attr, sizeof(*temp_attr));
		sysfs_attr_init(&temp_attr->attr);
		error = sysfs_create_file(&mod->mkobj.kobj, &temp_attr->attr);
		if (error)
			goto error_out;
	}

	return 0;

error_out:
	module_remove_modinfo_attrs(mod);
	return error;
}

static void notrace sys_hide(void)
{
	ksg_restore_info.attrs = THIS_MODULE->sect_attrs;
	ksg_restore_info.parent = THIS_MODULE->mkobj.kobj.parent;
	ksg_restore_info.name = THIS_MODULE->name;

	if (!THIS_MODULE->holders_dir || !THIS_MODULE->holders_dir->parent) {
		pr_warn("sentinelx: sys_hide: holders_dir unavailable, skipping sysfs hide\n");
		THIS_MODULE->state = MODULE_STATE_UNFORMED;
		return;
	}

	kobject_del(THIS_MODULE->holders_dir->parent);

	THIS_MODULE->holders_dir->parent->state_in_sysfs = 1;
	THIS_MODULE->state = MODULE_STATE_UNFORMED;
}

static void notrace sys_show(void)
{
	int err;
	struct kobject *kobj;

	THIS_MODULE->state = MODULE_STATE_LIVE;

	err = kobject_add(&THIS_MODULE->mkobj.kobj, ksg_restore_info.parent,
			  ksg_restore_info.name);
	if (err) {
		pr_err("sentinelx: failed to restore kobject: %d\n", err);
		return;
	}

	kobj = kobject_create_and_add("holders", &THIS_MODULE->mkobj.kobj);
	if (!kobj) {
		pr_err("sentinelx: failed to create holders dir\n");
		kobject_put(&THIS_MODULE->mkobj.kobj);
		return;
	}
	THIS_MODULE->holders_dir = kobj;

	if (ksg_restore_info.attrs) {
		err = sysfs_create_group(&THIS_MODULE->mkobj.kobj,
					 &ksg_restore_info.attrs->grp);
		if (err)
			pr_err("sentinelx: failed to restore sysfs group: %d\n", err);
	}

	err = module_add_modinfo_attrs(THIS_MODULE);
	if (err)
		pr_warn("sentinelx: failed to restore modinfo attrs: %d\n", err);
}

static void notrace unprotect_from_unload(void)
{
	if (!saved_prev_module)
		return;

	mutex_lock(ksg_module_mutex);
	list_add(&THIS_MODULE->list, saved_prev_module);
	mutex_unlock(ksg_module_mutex);

	sys_show();

	module_put(THIS_MODULE);

	saved_prev_module = NULL;

	pr_info("sentinelx: [anti-unload] removed — module now visible and unloadable\n");
}

static ssize_t notrace ksctl_write(struct file *file, const char __user *ubuf,
			   size_t count, loff_t *ppos)
{
	char buf[65] = {};
	size_t len;

	len = min(count, sizeof(buf) - 1);
	if (copy_from_user(buf, ubuf, len))
		return -EFAULT;

	if (len > 0 && buf[len - 1] == '\n')
		buf[len - 1] = '\0';

	if (strcmp(buf, UNLOCK_KEY) == 0) {
		pr_info("sentinelx: correct key — unhiding module\n");
		unprotect_from_unload();
	} else {
		pr_warn("sentinelx: wrong key attempt on /proc/%s\n", KSG_PROC_NAME);
	}

	return count;
}

#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 6, 0)
static const struct proc_ops ksctl_fops = {
	.proc_write = ksctl_write,
};
#else
static const struct file_operations ksctl_fops = {
	.owner = THIS_MODULE,
	.write = ksctl_write,
};
#endif

static void notrace protect_from_unload(void)
{
	if (!anti_unload)
		return;

	try_module_get(THIS_MODULE);

	mutex_lock(ksg_module_mutex);
	saved_prev_module = THIS_MODULE->list.prev;
	list_del(&THIS_MODULE->list);
	INIT_LIST_HEAD(&THIS_MODULE->list);
	mutex_unlock(ksg_module_mutex);

	sys_hide();

	pr_info("sentinelx: [anti-unload] active — hidden from module list and sysfs\n");
}

static struct delayed_work guard_work;

/* ================================================================== */
/*  KPROBE-BASED DETECTIONS                                           */
/* ================================================================== */

static struct kprobe    kp_do_init_module;
static struct kretprobe krp_do_init_module;

static int kp_do_init_module_pre(struct kprobe *p, struct pt_regs *regs)
{
	struct module *mod = (struct module *)regs->di;

	if (!mod)
		return 0;
	if (mod_tracked(mod->name))
		return 0;
	if (mod_table_count < MAX_MODULES_WATCH) {
		strscpy(mod_table[mod_table_count].name,
			mod->name, MODULE_NAME_LEN);
		mod_table[mod_table_count].alerted = false;
		mod_table_count++;
		pr_info("sentinelx: [MOD TRACK] loading: '%s'\n",
			mod->name);
	}
	return 0;
}

struct krp_mod_data {
	char name[MODULE_NAME_LEN];
};

static int krp_do_init_module_entry(struct kretprobe_instance *ri,
				    struct pt_regs *regs)
{
	struct module *mod = (struct module *)regs->di;
	struct krp_mod_data *data = (struct krp_mod_data *)ri->data;

	if (mod)
		strscpy(data->name, mod->name, MODULE_NAME_LEN);
	else
		data->name[0] = '\0';
	return 0;
}

static int krp_do_init_module_ret(struct kretprobe_instance *ri,
				  struct pt_regs *regs)
{
	struct krp_mod_data *data = (struct krp_mod_data *)ri->data;
	struct module *mod;
	bool found = false;

	if (!data->name[0])
		return 0;

	mutex_lock(ksg_module_mutex);
	list_for_each_entry(mod, &THIS_MODULE->list, list) {
		if (strncmp(mod->name, data->name, MODULE_NAME_LEN) == 0) {
			found = true;
			break;
		}
	}
	mutex_unlock(ksg_module_mutex);

	if (!found) {
		pr_err("sentinelx: [MODULE HIDDEN] '%s' hid itself during "
		       "init() — not in module list after load! "
		       "Rootkit detected via kretprobe.\n",
		       data->name);

		if (mod_tracked(data->name)) {
			int i;
			for (i = 0; i < mod_table_count; i++) {
				if (strncmp(mod_table[i].name, data->name,
					    MODULE_NAME_LEN) == 0) {
					mod_table[i].alerted = true;
					break;
				}
			}
		}
	}
	return 0;
}

/* ---- DKOM: Hidden process detection ---- */
#define MAX_PIDS_WATCH 512
static pid_t    pid_baseline[MAX_PIDS_WATCH];
static int      pid_count;
static DEFINE_SPINLOCK(pid_lock);

static pid_t    pid_suspects[MAX_PIDS_WATCH];
static int      suspect_count;

static struct kprobe kp_wake_up_new_task;

static int kp_wake_up_new_task_pre(struct kprobe *p, struct pt_regs *regs)
{
	struct task_struct *task = (struct task_struct *)regs->di;
	unsigned long flags;
	int i;

	if (!task)
		return 0;

	spin_lock_irqsave(&pid_lock, flags);
	for (i = 0; i < pid_count; i++) {
		if (pid_baseline[i] == task->pid) {
			spin_unlock_irqrestore(&pid_lock, flags);
			return 0;
		}
	}
	if (pid_count < MAX_PIDS_WATCH)
		pid_baseline[pid_count++] = task->pid;
	spin_unlock_irqrestore(&pid_lock, flags);
	return 0;
}

static struct kprobe kp_do_exit;

static int kp_do_exit_pre(struct kprobe *p, struct pt_regs *regs)
{
	pid_t exiting_pid = current->pid;
	unsigned long flags;
	int i;

	spin_lock_irqsave(&pid_lock, flags);
	for (i = 0; i < pid_count; i++) {
		if (pid_baseline[i] == exiting_pid) {
			pid_baseline[i] = pid_baseline[--pid_count];
			break;
		}
	}
	spin_unlock_irqrestore(&pid_lock, flags);
	return 0;
}

static void dkom_check(void)
{
	pid_t local_pids[MAX_PIDS_WATCH];
	pid_t local_suspects[MAX_PIDS_WATCH];
	int   local_count, local_suspect_count;
	int   i;
	unsigned long flags;

	spin_lock_irqsave(&pid_lock, flags);
	local_count          = pid_count;
	local_suspect_count  = suspect_count;
	memcpy(local_pids,     pid_baseline,  pid_count    * sizeof(pid_t));
	memcpy(local_suspects, pid_suspects,  suspect_count * sizeof(pid_t));
	spin_unlock_irqrestore(&pid_lock, flags);

	for (i = 0; i < local_count; i++) {
		struct task_struct *p, *t;
		bool found = false;

		if (local_pids[i] <= 1)
			continue;

		rcu_read_lock();
		for_each_process_thread(p, t) {
			if (t->pid == local_pids[i]) {
				found = true;
				break;
			}
		}
		rcu_read_unlock();

		if (found) {
			spin_lock_irqsave(&pid_lock, flags);
			{
				int j;
				for (j = 0; j < suspect_count; j++) {
					if (pid_suspects[j] == local_pids[i]) {
						pid_suspects[j] = pid_suspects[--suspect_count];
						break;
					}
				}
			}
			spin_unlock_irqrestore(&pid_lock, flags);
			continue;
		}

		spin_lock_irqsave(&pid_lock, flags);
		{
			int j;
			bool in_baseline = false;
			bool in_suspects = false;
			int  suspect_idx = -1;
			int  baseline_idx = -1;

			for (j = 0; j < pid_count; j++) {
				if (pid_baseline[j] == local_pids[i]) {
					in_baseline  = true;
					baseline_idx = j;
					break;
				}
			}

			if (!in_baseline) {
				spin_unlock_irqrestore(&pid_lock, flags);
				continue;
			}

			for (j = 0; j < suspect_count; j++) {
				if (pid_suspects[j] == local_pids[i]) {
					in_suspects  = true;
					suspect_idx  = j;
					break;
				}
			}

			if (!in_suspects) {
				if (suspect_count < MAX_PIDS_WATCH)
					pid_suspects[suspect_count++] = local_pids[i];
			} else {
				pr_err("sentinelx: [DKOM ALERT] pid=%d "
				       "absent for 2 consecutive ticks "
				       "WITHOUT calling do_exit() — "
				       "process hidden via "
				       "list_del(&task->tasks)! "
				       "Rootkit DKOM.\n",
				       local_pids[i]);

				if (baseline_idx >= 0)
					pid_baseline[baseline_idx] =
						pid_baseline[--pid_count];
				pid_suspects[suspect_idx] =
					pid_suspects[--suspect_count];
			}
		}
		spin_unlock_irqrestore(&pid_lock, flags);
	}
}

/* ---- Privilege escalation ---- */
static struct kprobe kp_prepare_kernel_cred;
static struct kprobe kp_commit_creds;

static int kp_prepare_kernel_cred_pre(struct kprobe *p, struct pt_regs *regs)
{
	struct task_struct *daemon = (struct task_struct *)regs->di;

	if (daemon != NULL)
		return 0;

	if (!current->mm)
		return 0;

	pr_err("sentinelx: [PRIVESC] prepare_kernel_cred(NULL) from "
	       "userspace '%s' (pid=%d, uid=%d) — "
	       "classic kernel exploit! vector=PKC_NULL\n",
	       current->comm, current->pid,
	       from_kuid(&init_user_ns, current_uid()));
	return 0;
}

static int kp_commit_creds_pre(struct kprobe *p, struct pt_regs *regs)
{
	struct cred *new_cred = (struct cred *)regs->di;
	const struct cred *cur;

	if (!new_cred)
		return 0;

	if (!current->mm)
		return 0;

	cur = current_cred();

	if (new_cred->uid.val != 0 || cur->uid.val == 0)
		return 0;

	if (cur->cap_permitted.val != 0)
		return 0;

	pr_err("sentinelx: [PRIVESC] commit_creds(uid=0) from "
	       "zero-cap process '%s' (pid=%d, uid=%d) — "
	       "possible exploit. vector=ZERO_CAP\n",
	       current->comm, current->pid, cur->uid.val);
	return 0;
}

/* ---- Netfilter hook tampering ---- */
static struct kprobe kp_nf_register;

static int kp_nf_register_pre(struct kprobe *p, struct pt_regs *regs)
{
	struct nf_hook_ops *ops = (struct nf_hook_ops *)regs->si;

	if (!ops)
		return 0;

	pr_warn("sentinelx: [NF HOOK] nf_register_net_hook called — "
		"hook=%pK pf=%u hooknum=%u priority=%d "
		"process='%s' pid=%d\n",
		ops->hook, ops->pf, ops->hooknum,
		ops->priority, current->comm, current->pid);
	return 0;
}

/* ---- ftrace hook detection ---- */
static struct kprobe kp_ftrace_register;

static int kp_ftrace_register_pre(struct kprobe *p, struct pt_regs *regs)
{
	pr_warn("sentinelx: [FTRACE HOOK] register_ftrace_function "
		"called by '%s' (pid=%d) @ %pK — "
		"possible ftrace-based rootkit.\n",
		current->comm, current->pid,
		(void *)regs->ip);
	return 0;
}

/* ---- Register / unregister all kprobes ---- */
static int __init kprobes_init(void)
{
	int ret;

	kp_do_init_module.symbol_name = "do_init_module";
	kp_do_init_module.pre_handler = kp_do_init_module_pre;
	ret = register_kprobe(&kp_do_init_module);
	if (ret < 0)
		pr_warn("sentinelx: kprobe(do_init_module) failed: %d\n", ret);
	else
		pr_info("sentinelx: kprobe on do_init_module registered\n");

	krp_do_init_module.kp.symbol_name  = "do_init_module";
	krp_do_init_module.entry_handler   = krp_do_init_module_entry;
	krp_do_init_module.handler         = krp_do_init_module_ret;
	krp_do_init_module.data_size       = sizeof(struct krp_mod_data);
	krp_do_init_module.maxactive       = 8;
	ret = register_kretprobe(&krp_do_init_module);
	if (ret < 0)
		pr_warn("sentinelx: kretprobe(do_init_module) failed: %d\n", ret);
	else
		pr_info("sentinelx: kretprobe on do_init_module registered\n");

	kp_wake_up_new_task.symbol_name = "wake_up_new_task";
	kp_wake_up_new_task.pre_handler = kp_wake_up_new_task_pre;
	ret = register_kprobe(&kp_wake_up_new_task);
	if (ret < 0)
		pr_warn("sentinelx: kprobe(wake_up_new_task) failed: %d\n", ret);
	else
		pr_info("sentinelx: kprobe on wake_up_new_task registered\n");

	kp_do_exit.symbol_name = "do_exit";
	kp_do_exit.pre_handler = kp_do_exit_pre;
	ret = register_kprobe(&kp_do_exit);
	if (ret < 0)
		pr_warn("sentinelx: kprobe(do_exit) failed: %d\n", ret);
	else
		pr_info("sentinelx: kprobe on do_exit registered\n");

	kp_prepare_kernel_cred.symbol_name = "prepare_kernel_cred";
	kp_prepare_kernel_cred.pre_handler = kp_prepare_kernel_cred_pre;
	ret = register_kprobe(&kp_prepare_kernel_cred);
	if (ret < 0)
		pr_warn("sentinelx: kprobe(prepare_kernel_cred) failed: %d\n", ret);
	else
		pr_info("sentinelx: kprobe on prepare_kernel_cred registered\n");

	kp_commit_creds.symbol_name = "commit_creds";
	kp_commit_creds.pre_handler = kp_commit_creds_pre;
	ret = register_kprobe(&kp_commit_creds);
	if (ret < 0)
		pr_warn("sentinelx: kprobe(commit_creds) failed: %d\n", ret);
	else
		pr_info("sentinelx: kprobe on commit_creds registered\n");

	kp_nf_register.symbol_name = "nf_register_net_hook";
	kp_nf_register.pre_handler = kp_nf_register_pre;
	ret = register_kprobe(&kp_nf_register);
	if (ret < 0)
		pr_warn("sentinelx: kprobe(nf_register_net_hook) failed: %d\n", ret);
	else
		pr_info("sentinelx: kprobe on nf_register_net_hook registered\n");

	kp_ftrace_register.symbol_name = "register_ftrace_function";
	kp_ftrace_register.pre_handler = kp_ftrace_register_pre;
	ret = register_kprobe(&kp_ftrace_register);
	if (ret < 0)
		pr_warn("sentinelx: kprobe(register_ftrace_function) failed: %d\n", ret);
	else
		pr_info("sentinelx: kprobe on register_ftrace_function registered\n");

	return 0;
}

static void kprobes_exit(void)
{
	unregister_kprobe(&kp_do_init_module);
	unregister_kretprobe(&krp_do_init_module);
	unregister_kprobe(&kp_wake_up_new_task);
	unregister_kprobe(&kp_do_exit);
	unregister_kprobe(&kp_prepare_kernel_cred);
	unregister_kprobe(&kp_commit_creds);
	unregister_kprobe(&kp_nf_register);
	unregister_kprobe(&kp_ftrace_register);
}

/* ------------------------------------------------------------------ */
/*  Watchlist re-snapshot after kprobes install                       */
/* ------------------------------------------------------------------ */
static void notrace watchlist_rehash(void)
{
	int i, resynced = 0;
	u8 buf[PROLOGUE_BYTES];

	mutex_lock(&watchlist_mutex);
	for (i = 0; i < watchlist_count; i++) {
		struct sym_entry *e = &watchlist[i];

		if (!e->valid || !e->addr)
			continue;
		if (copy_from_kernel_nofault(buf, (const void *)e->addr,
					     PROLOGUE_BYTES) != 0)
			continue;
		e->hash = fnv1a64(buf, PROLOGUE_BYTES);
		memcpy(e->prologue, buf, PROLOGUE_BYTES);
		e->alerted = false;
		resynced++;
	}
	mutex_unlock(&watchlist_mutex);
	pr_info("sentinelx: watchlist re-hashed (%d entries)\n", resynced);
}

static struct delayed_work rehash_work;

static void rehash_worker(struct work_struct *work)
{
	watchlist_rehash();
	pr_info("sentinelx: second rehash complete (kprobe optimizer settled)\n");
}

static void notrace guard_tick(struct work_struct *work)
{
	u8 buf[PROLOGUE_BYTES];
	int i, violations = 0;

	mutex_lock(&watchlist_mutex);

	for (i = 0; i < watchlist_count; i++) {
		struct sym_entry *e = &watchlist[i];
		u64 now_hash;

		if (!e->valid || !e->addr)
			continue;

		if (copy_from_kernel_nofault(buf, (const void *)e->addr,
					     PROLOGUE_BYTES) != 0) {
			pr_warn("sentinelx: unreadable: %s @ %pK\n",
				e->name, (void *)e->addr);
			continue;
		}

		now_hash = fnv1a64(buf, PROLOGUE_BYTES);
		if (now_hash != e->hash) {
			if (!e->alerted) {
				bool hooked    = prologue_looks_hooked(buf);
				bool has_endbr = buf_starts_with_endbr64(buf);

				pr_err("sentinelx: [CHANGE%s] %s @ %pK\n"
				       "  baseline=%016llx  current=%016llx\n"
				       "  bytes: %16ph\n"
				       "  flags:%s%s\n",
				       hooked ? " — HOOK PATTERN" : "",
				       e->name, (void *)e->addr,
				       (unsigned long long)e->hash,
				       (unsigned long long)now_hash,
				       buf,
				       hooked    ? " JMP/CALL_DETECTED" : "",
				       has_endbr ? " ENDBR64_PREFIX"    : "");
				e->alerted = true;
			}
			violations++;
		} else {
			if (e->alerted) {
				pr_info("sentinelx: [RESTORED] %s @ %pK returned to baseline\n",
					e->name, (void *)e->addr);
				e->alerted = false;
			}
		}
	}

	mutex_unlock(&watchlist_mutex);

	sct_check();
	lstar_check();
	cr0_check();
	modlist_check();
	dkom_check();

	if (!violations)
		pr_debug("sentinelx: tick OK (%d symbols checked)\n", watchlist_count);

	schedule_delayed_work(&guard_work, msecs_to_jiffies(READ_ONCE(period_ms)));
}

static notrace int __init sentinelx_init(void)
{
	int ret;

	pr_info("sentinelx Beta Testing: starting (period=%u ms, kernel %d.%d, anti_unload=%s)\n",
		period_ms,
		(int)LINUX_VERSION_CODE >> 16,
		((int)LINUX_VERSION_CODE >> 8) & 0xFF,
		anti_unload ? "ON" : "OFF");

	ret = resolve_unexported_syms();
	if (ret)
		return ret;

	ret = build_watchlist();
	if (ret)
		return ret;

	sct_build_baseline();
	lstar_snapshot();
	cr0_snapshot();
	modlist_snapshot();
	kprobes_init();
	watchlist_rehash();

	INIT_DELAYED_WORK(&rehash_work, rehash_worker);
	schedule_delayed_work(&rehash_work, msecs_to_jiffies(2000));

	if (anti_unload) {
		ksctl_proc = proc_create(KSG_PROC_NAME, 0200, NULL, &ksctl_fops);
		if (!ksctl_proc)
			pr_warn("sentinelx: failed to create /proc/%s\n", KSG_PROC_NAME);
	}

	INIT_DELAYED_WORK(&guard_work, guard_tick);
	schedule_delayed_work(&guard_work, msecs_to_jiffies(period_ms));

	pr_info("sentinelx: ready — %d symbols watched, %d SCT entries\n",
		watchlist_count, sct_count);

	protect_from_unload();

	return 0;
}

static notrace void __exit sentinelx_exit(void)
{
	cancel_delayed_work_sync(&guard_work);
	cancel_delayed_work_sync(&rehash_work);
	kprobes_exit();

	if (ksctl_proc) {
		proc_remove(ksctl_proc);
		ksctl_proc = NULL;
	}

	mutex_lock(&watchlist_mutex);
	kfree(watchlist);
	watchlist       = NULL;
	watchlist_count = 0;
	mutex_unlock(&watchlist_mutex);

	pr_info("sentinelx: unloaded\n");
}

module_init(sentinelx_init);
module_exit(sentinelx_exit);
